#!/usr/bin/env python3
"""Regenerate FILES.md — the annotated inventory of every file in the repository.

Descriptions live here rather than in the generated file, so FILES.md is never edited
by hand and can never drift from what is actually on disk. A file present on disk but
missing from DESC is reported, so new modules cannot be silently undocumented.
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

DESC: dict[str, str] = {
    "README.md": "Front page: what this is, headline numbers, limitations. The 'only ambassador'.",
    "CHANGELOG.md": "Release notes: what was measured, every bug fixed during the build, known gaps.",
    "FILES.md": "This inventory (generated by scripts/gen_manifest.py).",
    "Makefile": "All entry points. `make reproduce` regenerates every published number.",
    "requirements.txt": "pydantic, requests, lxml (core); anthropic (LLM path only); pytest.",
    ".gitignore": "Ignores downloads/caches. Reports ARE tracked — they are the evidence.",
    "LICENSE": "Apache License 2.0 — covers the code.",
    "LICENSE-DATA": "CC BY 4.0 for extracted data, plus what the licences do not cover.",
    "docs/HANDOVER.md": "Start here. Build record, all 8 findings with numbers, next actions, traps.",
    "docs/DECISIONS.md": "21 design decisions, each with alternative and cost. D21 = the big fix.",
    "docs/BENCHMARKS.md": "Metric definitions, full results, 3 ablations, QA audit, diagnostic benchmark.",
    "docs/ERROR_LEDGER.md": "10 of our error classes + 4 gold-data error classes, with measured rates.",
    "docs/LICENSING.md": "What we read, what we publish, per-tier rules, and what a lawyer might have won.",
    "docs/SCHEMA.md": "Schema v1 field reference and phenopacket compatibility policy.",
    "docs/REQUIREMENTS.md": "§1 requirements proven by measurement; §2 literature synthesis NOT done.",
    "docs/REPRODUCE.md": "Reproducing every number, determinism guarantees, common failures.",
    "docs/img/ui_before_phenotype_root_fix.png": "Evidence: chips show 'Affected', 'Bilateral', inheritance terms.",
    "docs/img/ui_after_phenotype_root_fix.png": "Evidence: same query, only real phenotypes.",
    "rdcd/__init__.py": "Package marker.",
    "rdcd/schema.py": "Schema v1: provenance-carrying, phenopacket round-trippable.",
    "rdcd/corpus/__init__.py": "Package marker.",
    "rdcd/corpus/ncbi.py": "All network I/O: rate-limited, disk-cached, licence captured at fetch.",
    "rdcd/corpus/jats.py": "JATS XML -> sectioned text with stable char offsets. Tables first-class.",
    "rdcd/ontology/__init__.py": "Package marker.",
    "rdcd/ontology/obo.py": "Compact OBO reader + pickle cache. Handles MONDO's xref modifiers.",
    "rdcd/ontology/store.py": "HPO/MONDO/HGNC/HPOA, information content, gene-disease, inheritance.",
    "rdcd/ontology/grounding.py": "Dictionary grounding + NegEx negation. Root-restricted to HP:0000118.",
    "rdcd/extract/__init__.py": "Package marker.",
    "rdcd/extract/base.py": "Extractor protocol; licence-gated evidence construction.",
    "rdcd/extract/baseline.py": "Dictionary baseline — the measured floor. No API key.",
    "rdcd/extract/llm.py": "LLM extractor: quotes in, ontology IDs out. Batch API + prompt caching.",
    "rdcd/eval/__init__.py": "Package marker.",
    "rdcd/eval/goldsets.py": "Gold phenopacket loading + licence/retraction availability audit.",
    "rdcd/eval/evalset.py": "Track SINGLE/PAPER construction, PMID-hash dev/test split.",
    "rdcd/eval/metrics.py": "Exact + ontology-aware graded F1, thresholded, bootstrap CIs.",
    "rdcd/eval/harness.py": "Offline scoring runs; embeds git rev + platform in every report.",
    "rdcd/eval/diagnose.py": "Phenotype -> disease ranker for the ceiling/pipeline measurement.",
    "rdcd/qa/__init__.py": "Package marker.",
    "rdcd/qa/provenance.py": "Re-reads every cited span: does it support the claim?",
    "rdcd/qa/constraints.py": "Machine-checkable impossibilities. ERROR vs WARN honestly separated.",
    "rdcd/qa/consensus.py": "Tri-model agreement -> published confidence + review queue.",
    "rdcd/qa/distant.py": "Distant supervision from abstract-stated diagnoses (regression detector).",
    "rdcd/qa/retractions.py": "Retraction Watch + PubMed pt + PMC OA flag. 94,265 notices.",
    "scripts/audit_goldset.py": "The licence/retraction audit -> goldset_availability.json.",
    "scripts/fetch_eval_fulltext.py": "Warms the full-text cache so scoring is offline.",
    "scripts/run_eval.py": "Scores an extractor; --all-sections/--no-*-synonyms/--no-phenotype-root ablations.",
    "scripts/run_qa_audit.py": "Audits gold AND predictions -> qa_audit.json.",
    "scripts/run_diagnostic_benchmark.py": "Ceiling vs pipeline top-k recall — the §6 proof.",
    "scripts/build_release.py": "Versioned release: JSONL + phenopackets + datasheet + SHA256SUMS.",
    "scripts/serve_api.py": "Read API + reference UI (stdlib only). The instrument that found D21.",
    "scripts/gen_manifest.py": "Regenerates FILES.md from disk.",
    "tests/conftest.py": "Skips ontology-dependent tests cleanly before `make data`.",
    "tests/test_schema.py": "Round-trip and provenance-or-null enforcement.",
    "tests/test_ontology.py": "OBO parsing, xref modifiers, negation, HP:0000118 restriction.",
    "tests/test_metrics.py": "Graded-F1 identity under summation, threshold floor, bootstrap determinism.",
    "tests/test_qa.py": "Constraint severities, ISO weeks, consensus weighting.",
    "tests/test_llm_extractor.py": "Request shape, cache stability, hallucinated-quote rejection.",
}

REPORTS = {
    "goldset_availability.json": "Per-paper PMC/OA/licence/retraction status for all 1,733 gold sources.",
    "eval_baseline.json": "Baseline scores, all tracks/splits, with bootstrap CIs.",
    "eval_ablation_no_pheno_root.json": "Ablation: grounding unrestricted (-0.118 F1).",
    "eval_ablation_all_sections.json": "Ablation: no patient-section filter (-0.038 F1).",
    "eval_ablation_no_related_syn.json": "Ablation: no multiword RELATED synonyms (-0.0001 F1).",
    "qa_audit.json": "Provenance rates, constraint violations (gold + predictions), retractions.",
    "diagnostic_benchmark_single.json": "Ceiling vs pipeline top-k recall + per-case ranks.",
    "audit_goldset.log": "Audit run log.",
}

RELEASE = {
    "cases.jsonl": "CaseRecords, schema v1, one per line, with provenance.",
    "phenopackets.jsonl": "The same records as GA4GH Phenopackets v2.",
    "sources.jsonl": "Per-source identifiers, licence, tier, retraction status.",
    "manifest.json": "Counts, input versions, build environment, caveat.",
    "DATASHEET.md": "What it is, how made, licence tiers, limitations, intended use.",
    "SHA256SUMS": "Checksums for every file above.",
}

SKIP_DIRS = {"data", ".git", "__pycache__", ".pytest_cache", "reports"}


def line_count(p: Path) -> int | None:
    try:
        with p.open(encoding="utf-8", errors="ignore") as fh:
            return sum(1 for _ in fh)
    except Exception:  # noqa: BLE001
        return None


def size_cell(p: Path) -> str:
    if p.suffix == ".png":
        return f"{p.stat().st_size // 1024} KB"
    n = line_count(p)
    return str(n) if n is not None else "—"


def on_disk() -> list[str]:
    out = []
    for p in sorted(ROOT.rglob("*")):
        if not p.is_file():
            continue
        rel = p.relative_to(ROOT)
        if set(rel.parts) & SKIP_DIRS or rel.name.endswith((".pyc", ".DS_Store")):
            continue
        if rel.parts[0] in ("data",):
            continue
        out.append(str(rel))
    return out


def main() -> None:
    files = on_disk()
    undocumented = [f for f in files if f not in DESC]
    stale = [f for f in DESC if not (ROOT / f).exists()]

    lines = [
        "# File manifest", "",
        "Every file, what it is, and how big. Generated — do not edit by hand:",
        "`python3 scripts/gen_manifest.py`.", "",
    ]
    groups = [
        ("Top level", lambda f: "/" not in f),
        ("Documentation (`docs/`)", lambda f: f.startswith("docs/")),
        ("Library (`rdcd/`)", lambda f: f.startswith("rdcd/")),
        ("Entry points (`scripts/`)", lambda f: f.startswith("scripts/")),
        ("Tests (`tests/`)", lambda f: f.startswith("tests/")),
    ]
    for title, pred in groups:
        sel = sorted(f for f in files if pred(f))
        if not sel:
            continue
        lines += [f"## {title}", "", "| File | Lines | Purpose |", "|---|---:|---|"]
        for f in sel:
            lines.append(f"| `{f}` | {size_cell(ROOT / f)} | {DESC.get(f, '**UNDOCUMENTED**')} |")
        lines.append("")

    rep = ROOT / "reports"
    if rep.exists():
        lines += ["## Generated evidence (`reports/`)", "",
                  "Tracked, not ignored: these are the evidence behind every number quoted in",
                  "`docs/`. Regenerate with `make reproduce`.", "",
                  "| File | Size | Contents |", "|---|---:|---|"]
        for f in sorted(rep.iterdir()):
            if f.is_file() and f.name in REPORTS:
                lines.append(f"| `reports/{f.name}` | {f.stat().st_size // 1024} KB | {REPORTS[f.name]} |")
        lines.append("")

    rels = ROOT / "data" / "releases"
    if rels.exists() and any(rels.iterdir()):
        rel = sorted(rels.iterdir())[-1]
        lines += [f"## Dataset release (`data/releases/{rel.name}/`)", "",
                  "Not tracked in git (regenerable with `make release`); shipped as a separate archive.",
                  "", "| File | Size | Contents |", "|---|---:|---|"]
        for f in sorted(rel.iterdir()):
            if f.name in RELEASE:
                lines.append(f"| `{f.name}` | {f.stat().st_size / 1e6:.2f} MB | {RELEASE[f.name]} |")
        lines.append("")

    lines += ["## Not in the repository", "", "| Path | Why |", "|---|---|",
              "| `data/ontologies/` (206 MB) | Downloaded by `make data-ontologies`. |",
              "| `data/goldsets/` (110 MB) | phenopacket-store 0.1.27, by `make data-goldsets`. |",
              "| `data/cache/` (132 MB) | HTTP cache. Makes scoring reproducible; rebuilt by `make fetch-fulltext`. |",
              "| `data/releases/` (21 MB) | Built by `make release`. |", ""]

    (ROOT / "FILES.md").write_text("\n".join(lines))
    print(f"wrote FILES.md — {len(files)} files documented")
    if undocumented:
        print("UNDOCUMENTED (add to DESC in this script):")
        for f in undocumented:
            print("   ", f)
    if stale:
        print("STALE entries in DESC (file no longer exists):")
        for f in stale:
            print("   ", f)
    if undocumented or stale:
        sys.exit(1)


if __name__ == "__main__":
    main()
